{% set name = "sativa" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/amkozlov/sativa/archive/refs/tags/v{{ version }}.zip
  sha256: e1ba4a89937dad23115575c0f6d185527ad1bb062b3fdd313a151492c21a6e2b

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('sativa', max_pin="x.x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - python >=3.0.0
  run:
    - python >=3.0.0

test:
  imports:
    - unittest
  commands:
#    - python sativa.py -h
    - python -m unittest discover -v

about:
   home: https://github.com/amkozlov/sativa
   license: GPL-3.0-or-later
   license_family: GPL3
   summary: "SATIVA Semi-Automatic Taxonomy Improvement and Validation Algorithm"

extra:
   identifiers:
     - doi:10.1093/nar/gkw396
