{% set name = "pyabpoa" %}
{% set version = "1.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/yangao07/abPOA/releases/download/v{{ version }}/abPOA-v{{ version }}.tar.gz
  sha256: c6e9f6e1e8938f5ecb47ef41c2571f3563fd7fdf5eb32e9500099cbd29e72612

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - zlib
  run:
    - python

test:
  imports:
    - pyabpoa

about:
  home: https://github.com/yangao07/abPOA
  summary: 'pyabpoa: SIMD-based partial order alignment using adaptive band'
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bkille
  identifiers:
    - doi:10.1093/bioinformatics/btaa963
    - biotools:abpoa
