{% set version = "0.4.0" %}
{% set sha256 = "4aab58bfaf8fee2ec12297cb1b11c64feffca0b36b906b14185da782bfadbfb0" %}

package:
  name: tksm
  version: {{ version }}

source:
  - url: https://github.com/vpc-ccg/tksm/archive/v{{ version }}.zip
    sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py < 3.8 or osx]
  run_exports:
    - {{ pin_subpackage('tksm', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - python {{ python }}
    - zlib
    - cxxopts >=3.1.0
    - fmt >=9.1.0
  run:
    - python {{ python }}
    - zlib
    - python-edlib
    - numpy
    - joblib
    - tqdm
    - scikit-learn

test:
  commands:
    - tksm sequence --help

about:
  home: https://github.com/vpc-ccg/tksm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Very modular, very cool long-read transcriptomic simulator
