{% set version = "1.0.0" %}

package:
  name: orthanq
  version: {{ version }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("orthanq", max_pin="x") }}

source:
  url: https://github.com/orthanq/orthanq/archive/v{{ version }}.tar.gz
  sha256: 

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - rust >=1.54
    - pkg-config
    - make
    - cmake
  host:
    - gsl
    - libcblas
    - openssl
    - zlib
    - bzip2
    - xz
    - clangdev
    - coincbc
    - hdf5 =1.10.5
  run:
    - gsl
    - libcblas
    - openssl
    - zlib
    - bzip2
    - xz
    - clangdev
    - coincbc
    - hdf5 =1.10.5

test:
  commands:
    - orthanq -h

about:
  home: https://github.com/orthanq/orthanq
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Uncertainty aware HLA typing and general haplotype quantification
