{% set version = "1.5.1" %}
{% set sha256 = "4f310fc200366f15fa45852ef6618a350cf1bdeb4a8c86023b3a07a8cb9e049d" %}

package:
  name: hmftools-pave
  version: '{{ version }}'

source:
  url: 'https://github.com/hartwigmedical/hmftools/releases/download/pave-v{{ version }}/pave_v{{ version }}.jar'
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage('hmftools-pave', max_pin="x.x") }}

requirements:
  run:
    - zlib
    - openjdk >=8

test:
  commands:
    - 'pave 2>&1 | grep -q "pave version"'

about:
  home: https://github.com/hartwigmedical/hmftools/tree/master/pave
  license: GPL-3.0-only
  license_family: GPL3
  summary: Pave annotates a somatic variant VCF with gene and transcript coding and protein effects.
