{% set name = "LTR_retriever" %}
{% set version = "2.9.8" %}
{% set sha256 = "c5723c69c8897e717f03a7a0690a8f9b4a6c56991d947eddb224066ddf2d1448" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/oushujun/LTR_retriever/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic

channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
  
requirements:
  run:
    - perl-text-soundex
    - perl
    - cd-hit
    - repeatmasker <4.1.5
    - rmblast <2.11
    - libstdcxx-ng <13
    - tesorter

test:
  commands:
    - LTR_retriever -h 2>&1 | grep -i usage

about:
  home: https://github.com/oushujun/LTR_retriever
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: Sensitive and accurate identification of LTR retrotransposons
  dev_url: https://github.com/oushujun/LTR_retriever
