{% set name = "xengsort" %}
{% set version = "2.0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 3b2b0cf13a4d29fbd5fca26237e9140dc54b246c7d3e2e801e5e7edf48d133d5

build:
  number: 0
  entry_points:
    - xengsort = xengsort.xengsort.xengsort_main:main
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.10
  run:
    - python >=3.10
    - numpy >=1.22
    - numba >=0.56
    - zarr
    - pytest
    - pyyaml
    - jsonargparse

test:
  imports:
    - xengsort
  commands:
    - xengsort --help
    - xengsort index --help
    - xengsort classify --help

about:
  home: https://gitlab.com/genomeinformatics/xengsort
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: "A fast xenograft read sorter based on space-efficient k-mer hashing"

extra:
  identifiers:
      - doi:10.4230/LIPIcs.WABI.2020.4
  recipe-maintainers:
    - JZentgraf
